name: Send Discord Notification

on:
  release:
    types:
      - published

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "## {{ github.release.name }}\n{{ github.release.body }}"

  
