name: Send Discord Notification

on:
  release:
    types: [published] # Triggers only when a release is published

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            # ${{ github.event.release.name }}
            ${{ github.event.release.body }}
